### ISSUE TITLE
Plans to update to Play version 2.6?

### ISSUE THREAD

**Issue by DanielSOhara27** [adrianhurt/play-multidomain-seed#10]
First of all, great tutorial and very helpful to a completely new developer just starting to learn how to use the framework.  However, your last commit was on Nov 2016 and for Play version 2.5. Are you still maintaining this repo and updating for version 2.6? 

For someone completely illiterate to Scala, but very knowledgeable of Java, could you point out any major points I should watch out for when translating your project into a hybrid Java/Scala?

Thanks.

P.S. I realize that Scala also works with the JVM, but I don't really have the time to learn Scala natively atm.

**Comment by adrianhurt** [comment]
Hi @DanielSOhara27,

Yes, my intention is to keep all my repos updated, but unfortunately I don't have so much free time… So I'll update it as soon as possible.

Regarding to mixing Java and Scala code, I think you can do it directly without any problems. I've never test it (I changed to Scala directly with Play 2 and I'm forgetting Java more quickly than I'm learning Scala, hahaha).  I only know you have to take into account some things to interoperate between Java and Scala. I've just found these links googling during a minute, so I suppose you could find better information:
- http://lampwww.epfl.ch/~michelou/scala/using-scala-from-java.html
- http://blog.muhuk.com/2016/05/24/how_to_call_scala_from_java__using_scala_classes.html#.WXtg4cYrxTY
- http://www.codecommit.com/blog/java/interop-between-java-and-scala

Happy coding!
