### ISSUE TITLE
How to use Global[Subproject].scala in Global.scala?

### ISSUE THREAD

**Issue by garrrio** [adrianhurt/play-multidomain-seed#2]
Compilation error
not found: value GlobalWeb

**Comment by adrianhurt** [comment]
Hello @garrrio,

Sorry, but I don't understand your problem. Is it an issue for the specific code of this repository? I've just tried again and I don't have any compilation error. And __Global__ object calls correctly __GlobalAdmin__ and __GlobalWeb__. Or is it a error you get in your code trying to adapt this structure? If so, I can't know the problem without your code. Try to check that every configuration file, probably you have missed some configuration, specially with files:

* build.sbt
* project/build.properties
* project/plugins.sbt
* project/Common.scala
* app/Global.scala
* conf/application.conf
* modules/common/build.sbt
* modules/common/conf/application.conf
* modules/admin/build.sbt
* modules/admin/app/GlobalAdmin.scala
* modules/admin/conf/application.conf
* modules/web/build.sbt
* modules/web/app/GlobalAdmin.scala
* modules/web/conf/application.conf

**Comment by garrrio** [comment]
@adrianhurt I'm trying to adapt this structure and your answer is exactly what I need. Thank you very much.

**Comment by adrianhurt** [comment]
you're welcome!
