### ISSUE TITLE
Any plan to update to 2.4 ?

### ISSUE THREAD

**Issue by regisfoucault** [adrianhurt/play-multidomain-seed#4]

**Comment by adrianhurt** [comment]
Hi @regisfoucault. Yes, I'm trying now to update it in my free time, but I don't have enough and I'm getting more errors than I expected, so I suppose it will take me a few days. I don't have a deep knowledge about these specific topics of Play so it's a try-error work.

**Comment by regisfoucault** [comment]
I got a version which compiles, but it does not work ! In the meantime, I
use a workaround. Thanks for you work.

--
Régis Foucault
+336 85 36 88 20

2015-07-26 22:30 GMT+02:00 adrianhurt <notifications@github.com>:

**Comment by adrianhurt** [comment]
I think it's now correctly working for Play 2.4. There has been some main changes:
* `GlobalSettings` are now deprecated so they have been substituted by the corresponding `RequestHandler` and `ErrorHandler`.
* Any assets in sub projects are now by default placed into `/lib/[subproject]` to allow files with the same name in the root project / different subprojects without causing them to interfere with each other. It means that assets for admin subproject are located into `lib/admin` when you are running the whole project, but not when you run the admin subproject separately. To get that I have needed to implement a workaround rewriting the url within the global `RequestHandler` when running the whole project.
* Improvements with configuration files to avoid name collisions.
* Improvements with Assets to make the reverse routing easier.
* Added explanation of how to have shared resources

**Comment by regisfoucault** [comment]
thanks very much @adrianhurt  !
