### ISSUE TITLE
conf/routes no longer exists

### ISSUE THREAD

**Issue by bwbecker** [adrianhurt/play-multidomain-seed#6]
conf/routes is referenced a couple of places in the ReadMe but does not exist.  Examples:

```
 └ conf
   └ root-dev.conf
   └ routes
```

```
conf/routes (used when whole project is running): routes file for the whole project. It simply imports the routes file of every subproject.
```
Learning how to split the routes file in the transition from Play 2.3 to 2.4 is exactly why I'm here, so it's relevant (to me!).

That said, I just discovered the `VirtualHostRequestHandler` class and I'm pretty sure that's going to get me going towards a solution.  Thanks for the example!

**Comment by adrianhurt** [comment]
Hi @bwbecker. You're right. These references to that file are old, because now `VirtualHostRequestHandler` is in charge of delegate to each `modules/[subproject]/conf/[subproject].routes`.

**Comment by bwbecker** [comment]
Wow!  Thanks for the super-speedy confirmation of my hunch.

**Comment by adrianhurt** [comment]
And it's now fixed! 😄
