### ISSUE TITLE
How to add plugins to a Sub Project

### ISSUE THREAD

**Issue by venkatzifo** [adrianhurt/play-multidomain-seed#8]
I am not able to add a plugin to a sub project in this structure..is there way i can add plugins to a Sub Project...

Else it is ok even if i am able to add a plugin only to a root project and disable the plugin at sub projects level

**Comment by adrianhurt** [comment]
I'm so sorry for the loooong delay, @venkatzifo . I've had too busy months since then. I've just updated the seed to Play 2.5.

Did you resolve the issue? Do you mean a plugin that is within the `project/plugins.sbt` file? If so, I'm afraid I don't have any clue for this case...

**Comment by adrianhurt** [comment]
What a coincidence, right now I've just found this. Maybe it could be a clue to enable plugins only on a determinate module…

https://www.playframework.com/documentation/2.5.x/Migration23#auto-plugins-and-plugin-settings

**Comment by venkatzifo** [comment]
Hi Adrian,

Thanks for the help. I will try with the above information provided by you.
This project is fully developed on scala. You have Java version of this project ? If you have please share it ,it will be helpful for me. I am using play with java.

**Comment by adrianhurt** [comment]
No, sorry. I only use the Scala version since Play 2. However, this template is about how to configure the project, so I suppose the key things don't differ so much from the Java version.
